### ISSUE TITLE
Not able to see files on SD-card 

### ISSUE THREAD

**Issue by skasti** [grblHAL/Plugin_SD_card#4]
**Board:** Flexi-HAL with ethernet/sd expansion
**Firmware:**
https://github.com/Expatria-Technologies/STM32F4xx/releases/tag/flexi-hal-v1.0.0.6
`FLEXI_HAL_4AXIS_ETH_SD_PRB_20240604_060724.uf2`

**Sender:** ioSender 2.0.44

**Disclaimer:** I realize it is likely that this could be caused by the beta release, or maybe I did not do something right when updating firmware, but I still thought this was strange enough to create an issue. If nothing else, just so I can get an understanding of what I am doing wrong 😅 

**Description:** ioSender allowed me to upload a file (yModem, as I am using USB only), and it gives me the `uploading` and then `transfer done` messages in the status bar. But the file does not show up in ioSenders `SD Card`-tab. 
![image](https://github.com/user-attachments/assets/7bd3dfcf-e709-43d1-a8c6-92ce20a6aa9c)

I also do not get any response when running `$F`:
![image](https://github.com/user-attachments/assets/393c5f60-40b4-4858-9357-0d7292367119)
(i checked `verbose`, and I only get an `ok` response)

However, when extracting the SD-card, the files I have tried uploading were in fact there, and after re-inserting the sd-card, I was able to run a macro using `G65 P301` (`$F` and the `SD Card` tab in ioSender still show no files).
```
G65 P301
[MSG:Dropping Tool]
<Idle|MPos:-5.000,-5.000,-98.000,0.000|Bf:64,1024|FS:0,1500,510|Ov:100,100,100|A:C>
[GC:G0 G54 G17 G21 G90 G94 G49 G98 G50 M5 M9 T0 F0 S1500.]
<Idle|MPos:-5.000,-5.000,-98.000,0.000|Bf:64,1024|FS:0,1500,1500>
<Run|MPos:-5.000,-5.000,-99.178,0.000|Bf:60,1024|FS:1500,1500,1500>
[GC:G1 G54 G17 G21 G91 G94 G49 G98 G50 M4 M9 T0 F1500 S1500.]
<Run|MPos:-5.000,-5.000,-102.397,0.000|Bf:61,1024|FS:800,1500,1500>
[GC:G1 G54 G17 G21 G91 G94 G49 G98 G50 M4 M9 T0 F1500 S1500.]
<Run|MPos:-5.000,-5.000,-99.603,0.000|Bf:61,1024|FS:800,1500,1500>
<Run|MPos:-5.000,-5.000,-96.922,0.000|Bf:62,1024|FS:540,1500,1500>
<Run|MPos:-5.000,-5.000,-99.119,0.000|Bf:62,1024|FS:959,1500,1500>
<Run|MPos:-5.000,-5.000,-100.888,0.000|Bf:63,1024|FS:1500,1500,1500>
<Run|MPos:-5.000,-5.000,-96.031,0.000|Bf:64,1024|FS:0,1500,1500>
<Idle|MPos:-5.000,-5.000,-95.500,0.000|Bf:64,1024|FS:0,1500,1500|WCO:-189.481,-84.047,-102.291,0.000>
<Idle|MPos:-5.000,-5.000,-95.500,0.000|Bf:64,1024|FS:0,0,703|Ov:100,100,100|A:>
[GC:G1 G54 G17 G21 G91 G94 G49 G98 G50 M5 M9 T0 F1500 S1500.]
<Run|MPos:-5.000,-5.000,-95.428,0.000|Bf:63,1024|FS:1980,0,0>
[GC:G1 G54 G17 G21 G90 G94 G49 G98 G50 M5 M9 T0 F5000 S1500.]
<Run|MPos:-5.000,-5.000,-88.075,0.000|Bf:63,1024|FS:5000,0,0>
[GC:G1 G54 G17 G21 G90 G94 G49 G98 G50 M5 M9 T0 F5000 S1500.]
<Run|MPos:-5.000,-5.000,-71.869,0.000|Bf:63,1024|FS:5000,0,0>
<Run|MPos:-5.000,-5.000,-54.344,0.000|Bf:63,1024|FS:2840,0,0>
<Run|MPos:-5.000,-5.000,-45.775,0.000|Bf:64,1024|FS:0,0,0>
ok
<Idle|MPos:-5.000,-5.000,-45.500,0.000|Bf:64,1024|FS:0,0,0>
[GC:G1 G54 G17 G21 G90 G94 G49 G98 G50 M5 M9 T0 F5000 S1500.]
```

**Comment by terjeio** [comment]
Filetype?
`$F `outputs a [filtered](https://github.com/grblHAL/Plugin_SD_card/blob/847f3f38cfc07cc1c4c3a36e5d6e5db6ce5ff055/sdcard.c#L62-L73) list of files, if the file does not match the filter use `$F+` to list all files. Or select _View all_ in the popup menu available from the ioSender file list.
Note that the _macro_ filetype was recently added, and ioSender will soon get a more easy/visible way of selecting "view all files".

**Comment by skasti** [comment]
I think this is due to a bug in the pre-baked flexi-hal firmware, as it started working fine when I built the firmware myself with some tweaks. Not been able to reproduce it since, and did not notice which tweak fixed it! 😂
